### ISSUE TITLE
Does not start the script

### ISSUE THREAD

**Issue by crashzk** [martipartydev/Cs2-ReservedSlots#1]
I went through the entire installation process but it doesn't work.

![image](https://github.com/martipartydev/Cs2-ReservedSlots/assets/32937653/40b2f8c1-16af-4301-9e94-713f947be0c6)

**Comment by blu133721** [comment]
This is a LUA Script, not a meta plugin.

**Comment by martipartydev** [comment]
Follow the installation guide

**Comment by crashzk** [comment]
> Follow the installation guide 

I literally followed him.... In any case, I'll test it again.
