### ISSUE TITLE
KeyValues Error: RecursiveLoadFromBuffer:  got }

### ISSUE THREAD

**Issue by crywolfy** [martipartydev/Cs2-ReservedSlots#4]
L 11/13/2023 - 12:08:18: server_cvar: "sv_cheats" "true"
Resserved slots!
KeyValues Error: RecursiveLoadFromBuffer:  got } in key in file scripts/configs/reserved.ini
Reserved, 
Script failed to LoadKeyValues scripts/configs/reserved.ini
list start
Couldn't load config file (scripts/configs/reserved.ini). Adverts script wasn't started.

reserved.ini
"Reserved"
{
	"[U:1:25601320]"
}

What is wrong ? also will like to know how to add multiple steamid3 users

A lot of info is missing

**Comment by crashzk** [comment]
Try it like this:

```
"Reserved"
{
    "U:1:128024857"
    "U:1:128024857"
    "U:1:128024857"
}
```
If you get an error, try this:
```
"Reserved"
{
    "U:1:128024857",
    "U:1:128024857",
    "U:1:128024857"
}
```

**Comment by martipartydev** [comment]
You need to have space before the line with the steam id's also you can try experimenting with ", "

**Comment by crywolfy** [comment]
L 11/21/2023 - 16:00:39: server_cvar: "sv_cheats" "true"
Resserved slots!
KeyValues Error: RecursiveLoadFromBuffer:  got } in key in file scripts/configs/reserved.ini
Reserved, 
Script failed to LoadKeyValues scripts/configs/reserved.ini
list start
Couldn't load config file (scripts/configs/reserved.ini). Adverts script wasn't started.

Triyed
"Reserved"
{

	"[U:1:25601320]"

}
triyed
"Reserved"
{

	"[U:1:25601320],"
	"",
	""
}
With and without , , same error

Solved, if i have for solts mentioned in lua, the ini needs to have also four lines
ex:
"Reserved"
{

	"[U:1:25601320]"
	
	"",
	
	"",
	
	""
}

**Comment by martipartydev** [comment]
tell me if this work
